[theme]
primaryColor = "#06b6d4"
backgroundColor = "#090d16"
secondaryBackgroundColor = "#141518"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
